---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress-egress
  namespace: namespacea
spec:
  podSelector:
    matchLabels:
      tag: servicea
  policyTypes:
  - Ingress
  - Egress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-within-same-namespace
  namespace: namespacea
spec:
  podSelector:
    matchLabels:
      tag: servicea
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tag: servicea
  egress:
  - to:
    - podSelector:
        matchLabels:
          tag: servicea
...    