kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-within-same-namespace
  namespace: namespacea
spec:
  podSelector: 
    matchLabels:
      tag: servicea
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              tag: servicea
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              tag: servicea
  ports:
    - protocol: TCP
      port: 6379
